### ISSUE TITLE
ignoring essentials god

### ISSUE THREAD

**Issue by 100petr** [Seggan/Slimy-Power-Suits#3]
The plugin ignores god from the essentials plugin. 
Reproduction:
Turn god on (/god on)
Go to lava (in survival, with god mode)
It will kill you

If I have power suit armor, it won't kill me (with god).
![image](https://user-images.githubusercontent.com/29830635/95016389-00c69a80-0653-11eb-9ec3-ae5a59ef6c6a.png)
![image](https://user-images.githubusercontent.com/29830635/95016392-09b76c00-0653-11eb-9d3c-60923f4622be.png)
I'm sorry if it's not a bug.

**Comment by Seggan** [comment]
@100petr correct it is a bug. Relates to #4.

**Comment by Seggan** [comment]
fixed. build 6
