### ISSUE TITLE
Error console

### ISSUE THREAD

**Issue by ArrozElManko** [Seggan/Slimy-Power-Suits#6]
Hello, I have some problems that I get in the console and this error is a bit annoying, they told me to write a report here
https://imgur.com/nJMLNzm

**Comment by 100petr** [comment]
#2

**Comment by Seggan** [comment]
Good morning @ArrozElManko , as petr has already pointed out this is a duplicate of #2 . It has already been fixed locally and will be released in build 6. For now, ignore it as it is pretty much harmless.
